### ISSUE TITLE
Investigate allowing custom bot token assignment for upper Patreon tiers

### ISSUE THREAD

**Issue by MattTheDev** [MattTheDev/CouchBot#117]
1. Patreon purchased
2. Patreon role assigned
3. User DMs bot their custom bot token
4. Bot sets up backend settings, sends OK to user via DM
5. User then configures bot via their own bot, their own bot announces, etc.

Questions for Me - 

* What tier? This would add infrastructure needs for multiple instances of the bot to be running concurrently. More servers would need to be purchased.
* How can we align this with 1 instance of Antenna? Multiple would cause issues.

**Comment by SUPERCHIEFYT** [comment]
Perhaps.. a semi-easier option for customization since majority of the bot is just posting announcements.. maybe make a custom-webhook option for it (i.e: name and icon)

It's possible to send, edit & delete webhook messages (and lower ratelimits)
> The only thing you would have to store is the ID and token of the webhook. which is semi-safer than storing bot tokens

It doesn't require you to make an entire system to just customize that option of the bot and it would cost less overall. 

just an idea. 🤷‍♀️

**Comment by MattTheDev** [comment]
Decided against this. Centralized bot is best bot imo.
